language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - python setup.py install
  - pip install pylint
# command to run tests
script: pylint -E jdcloud_cli/controllers/services
